// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc369.Robot2017Code;

import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc369.Robot2017Code.commands.*;
import org.usfirst.frc369.Robot2017Code.subsystems.*;
import com.kauailabs.navx.frc.AHRS;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

    Command autonomousCommand;
    CommandGroup autoDrive;

    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static RobotHanger robotHanger;
    public static DriveSystem driveSys;
    public static driveByJoy drive;
    public static Compressor compressor;
    public static DoubleEncoder dblE;
    public static GearHandler gearHandler;
    public static AHRS ahrs;
    public static Joystick joy;
    public static GyroAngleHandler gyroAngle;
    
    
    public void robotInit() {
    RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        robotHanger = new RobotHanger(); 					//initialize new subsystem robothanger
        driveSys = new DriveSystem();						//initialize new subsystem DriveSystem
        gearHandler = new GearHandler();					//initialize new subsystem RobotHanger
        
        compressor = new Compressor();						//initialize new Compressor				
        compressor.setClosedLoopControl(true);				//start compressor cycle
        
        CameraServer.getInstance().startAutomaticCapture();	//start camera stream
        
        dblE = new DoubleEncoder();							//initialize new subsystem DoubleEncoders
        joy = new Joystick(2);								//joystick for testing mode

        oi = new OI();										//initialize new OI class variable "operator input"
    }


    public void disabledInit(){
    	
    }

    public void disabledPeriodic() {
        Scheduler.getInstance().run();
        SmartDashboard.putNumber("GYRO", RobotMap.gyro.getAngle());
    }

    public void autonomousInit() {
    	driveSys.resetAngle();
    	autonomousCommand = new PlaceGearAutonomous();
    	if (autonomousCommand != null) autonomousCommand.start();
    }

    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    public void teleopInit() {
        if (autonomousCommand != null) autonomousCommand.cancel();
        drive = new driveByJoy();
        drive.start();
    }


    public void teleopPeriodic() {
        Scheduler.getInstance().run();
    	driveSys.resetAngle();
    	dblE.reset();
    }

    public void testPeriodic() {
        LiveWindow.run();
        //THIS COMMAND WILL UPDATE THE VALUES OF PID ACCCORDING TO THE VALUES OF THE FIRST THREE
        //SLIDERS IN THE BASIC TAB ON THE DASHBOARD. START OFF WITH P:0.03/I:0.0/D:0.0
        //AND USE TEST ANGLE OF 90 DEGREES AND 0 DEGREES
        //IF THE ROBOT GOES PAST THE THE ANGLE TO ACQUIRE THEN DECREASE P e.g. 0.029, 0.028 etc
        //AND VICE VERSA FOR IF IT SLOWS DOWN BEFORE IT HITS ITS TARGET ANGLE e.g.: 0.031 
        if(SmartDashboard.getBoolean("DB/Button 0", false)){
	        driveSys.modPID(); 
	        if(joy.getRawButton(1))
	        	driveSys.rotateToAngle(90);
	        if(joy.getRawButton(2))
	        	driveSys.rotateToAngle(0);
	        if(joy.getRawButton(3))
	        	driveSys.resetAngle();
        }
        
        if(SmartDashboard.getBoolean("DB/Button 0", false)){
        	
        }        
    }
}
